### ISSUE TITLE
solidIGAex1.m

### ISSUE THREAD

**Issue by Batmanabcdefg** [CALFEM/calfem-matlab-iga#2]
Hi,

I have tested the input file "solidIGAex1.m"

Matlab shows  a bug:
Error using run (line 41)
.\..\NURBS\solid\data_solid6 not found.

can the following codes be added:
addpath('Solid');
run data_solid6

Kind regards, Yaakov

**Comment by vedadalic** [comment]
Hi,

What OS and version of Matlab and are you running? For me it works in Win10+R2015a and MacOS Sierra+R2016a.

Kind regards, Vedad

**Comment by Batmanabcdefg** [comment]
Hi,

I use Win10 + R2014a and Win10 +R2016a.

Kind regards,Yaakov

**Comment by vedadalic** [comment]
Does it help if you try enclosing the path in single quotes? Like this

run './../NURBS/solid/data_solid6.m'

And make sure that the matlab current folder is calfem-matlab-iga/examples/IGA

Otherwise it should work to just put both files in the same folder and remove the relative path to data_solid6.

**Comment by vedadalic** [comment]
I think I see what the problem is. Adding the examples folders to "Set Path" in matlab can cause issues. Will rewrite the installation instructions. 

In your matlab paths, remove all of the example folders from calfem-matlab-iga/examples/* and it should work!

Thank you for the report!

**Comment by Batmanabcdefg** [comment]
no problem ^_^, I would like to make contribution to improve calfem-matlab-iga!
